Vagrant.configure("2") do |config|

  # Imagen base
  config.vm.box = "ubuntu/jammy64"

  # Red privada (IP automática)
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "public_network"
  # Carpeta compartida (opcional pero recomendado)
  config.vm.synced_folder "./compartido", "/home/vagrant/compartido"

  # Configuración de VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "neptuno"
    vb.memory = "2048"
    vb.cpus = 2
  end

end