# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  # Red bridge
  config.vm.network "public_network"

  # Recursos
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4086"
    vb.cpus = 2
  end
  
config.vm.synced_folder "./compartido", "/home/vagrant/compartido"

  # Provisioning (instalación automática)
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update

    # instalar git
    sudo apt install -y git

  SHELL

end